version: '3.1'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 11111111
      MYSQL_DATABASE: test
      MYSQL_USER: root
      MYSQL_PASSWORD: 11111111
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql

  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile # Specify the Dockerfile if not in the root
      target: development # Specify the target build stage if you want to build a specific stage and not the final stage
    container_name: nestjs-aqixw-container
    restart: always
    ports:
      - "3030:3030"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: 11111111
      DB_NAME: test
    env_file:
      - .env.development
    volumes:
      - .:/usr/src/app
    command: npm run start:dev
